config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  root to: 'public#main'

  devise_for :accounts

  # site admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  # front-end version for unregistered users
  get '/blog', to: 'posts#latest', as: :blog

  # dashboard menu routes for registered users
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/profiles/:id', to: 'dashboard#profile', as: :profile

  # send email message to agent route
  post '/agent/message', to: 'properties#email_agent', as: :email_agent
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
  <%= link_to accounts_path, class: "nav-link" do %>
    <i class="fa-solid fa-chart-line text-muted"></i>
    Accounts
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <i class="fa-solid fa-house text-muted"></i>
    Properties
  <% end %>
</li>

<li class="nav-item">
  <%= link_to posts_path, class: "nav-link" do %>
    <i class="fa-solid fa-house text-muted"></i>
    Blog Posts
  <% end %>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users" aria-hidden="true">
      <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
      <circle cx="9" cy="7" r="4"></circle>
      <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
      <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
    </svg>
    Adverts
  </a>
</li>

app/views/layouts/nav/_dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">Property Finder</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "nav-link px-3" %>
    </div>
  </div>
</header>

app/views/layouts/nav/_dashboard_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">

<!--    show different sidebar for user or admin-->
    <ul class="nav flex-column">
      <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }" %>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to profile_path(current_account), class: "nav-link" do %>
          <i class="fa-solid fa-user text-muted"></i>
          My profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to edit_account_registration_path(current_account), class: "nav-link" do %>
          <i class="fa-solid fa-user text-muted"></i>
          Edit profile
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
  <div class="container">
    <a class="navbar-brand" href="/">Property Finder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link"  %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
        <% end %>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Latest</a>-->
<!--        </li>-->
        <li class="nav-item">
          <%= link_to "News", blog_path, class: "nav-link"  %>
        </li>

<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="dropdown07">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->

<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Advertising</a>-->
<!--        </li>-->

      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_account_session_path, method: :delete, class: 'btn btn-secondary' %>
          </li>
        <% else %>
          <li class="nav-item mx-2">
            <%= link_to "Log in", new_account_session_path, class: 'btn btn-secondary' %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to "Sign up", new_account_registration_path, class: 'btn btn-success' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
  <%= link_to dashboard_path, class: "nav-link active" do %>
    <i class="fa-solid fa-chart-line text-muted"></i>
    Dashboard
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <i class="fa-solid fa-house text-muted"></i>
    Properties
  <% end %>
</li>

<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers" aria-hidden="true">
      <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
      <polyline points="2 17 12 22 22 17"></polyline>
      <polyline points="2 12 12 17 22 12"></polyline>
    </svg>
    Viewings
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users" aria-hidden="true">
      <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
      <circle cx="9" cy="7" r="4"></circle>
      <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
      <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
    </svg>
    Contacts
  </a>
</li>