config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  root to: 'public#main'

  devise_for :accounts

  # site admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  # front-end version for unregistered users
  get '/blog', to: 'posts#latest', as: :blog

  # dashboard menu routes for registered users
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/profiles/:id', to: 'dashboard#profile', as: :profile

  # send email message to agent route
  post '/agent/message', to: 'properties#email_agent', as: :email_agent
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :account

  scope :latest, -> { order created_at: :desc }

  scope :sold, -> { where(for_sale: true, status: "sold") }
  scope :for_sale, -> { where(for_sale: true, status: "available") }
  scope :leased, -> { where(for_sale: false, status: "leased") }
  scope :for_rent, -> { where(for_sale: false, status: "available") }
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_account!, only: %i[new create destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # send email to agent function
  def email_agent
    # trigger email send
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    ContactMailer.email_agent( agent_id, first_name, last_name, email, message).deliver_now

    # response to script
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

  def set_sidebar
    @show_sidebar = true
  end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :photo, :status,
                                       :photo_cache, :parking_spaces, :details, :for_sale, :available_date)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_thumbnail property
    img = property.photo.present? ? property.photo.thumb.url : "property-placeholder.jpg"
    image_tag img, class: "property-thumb"
  end

  def property_thumbnail_url property
    property.photo.thumb.present? ? property.photo.thumb.url : asset_url("property-placeholder.jpg")
  end

  def property_photo_url property
    property.photo.present? ? property.photo.url : asset_url("property-placeholder.jpg")
  end
end

app/views/properties/_agent_details.html.erb
<div class="text-center border-1 p-3 ml-3">
  <div class="mb-2">
    <%= profile_picture agent %>
  </div>
  <h3 class="h4"><%= agent.full_name %></h3>
  <p><%= agent.company %></p>

  <div class="d-grid gap-2 mb-2">
    <button class="btn btn-block btn-info text-uppercase" id="show-tel" data-telephone="<%= agent.telephone %>"><i class="fa-solid fa-phone"></i><span>Call</span></button>
  </div>


  <%= link_to "Profile", profile_path(agent.id), class:"btn btn-secondary text-uppercase" %>
  <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#sendEmailModal">Email</button>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <%= render 'layouts/validation', item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select({'Yes' => true, 'No' => false}, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group">
    <% opts = @property.for_sale? ? {  'Available' => 'available', "Sold" => "sold"} : { 'Available' => 'available', "Leased" => "leased"} %>
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select(opts, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_date %>
    <%= form.date_field :available_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" %>
    <%= form.hidden_field :photo_cache %>

    <% if @property.photo.present? %>
      <%= image_tag @property.photo.thumb.url  %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
  <div class="col-4">
    <div class="property border">

      <div class="property-thumb" style="background-image: url(<%= property_thumbnail_url(property) %>)">
      <%= link_to "", property_path(property) %>
      </div>

      <div class="property-summary p-3">
        <h3 class="h3"><%= link_to property.name, property_path(property), class: "text-dark"%></h3>

        <span class="mx-2">
          <%= property.rooms %>
          <i class="fa-solid fa-bed mx-1 text-muted"></i>
        </span>
        <span class="mx-2">
          <%= property.bathrooms %>
          <i class="fa-solid fa-shower mx-1 text-muted"></i>
        </span>
        <span class="">
          <%= property.parking_spaces %>
          <i class="fa-solid fa-car mx-1 text-muted"></i>
          </span>

        <p class="mt-2"><%= property.address %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/_profile_details.html.erb
<div class="text-center border-1 p-3 ml-3">
  <div class="mb-2">
    <%= profile_picture @account %>
  </div>
  <h3 class="h4"><%= @account.full_name %></h3>
  <p><%= @account.company %></p>

  <button class="btn btn-info text-uppercase" id="show-tel" data-telephone="<%= @account.telephone %>">
    <i class="fa-solid fa-phone"></i><span>Call</span></button>

  <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#sendEmailModal">Email</button>
</div>

app/views/properties/_send_email_modal.html.erb
<div class="modal fade" id="sendEmailModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message for <%= agent.full_name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <%= form_tag email_agent_path, id: "email-agent" do %>
          <%= hidden_field_tag :agent_id, agent.id %>

          <div class="form-group">
            <label for="message-first-name" class="col-form-label">First Name:</label>
            <%= text_field_tag :first_name, nil, class: "form-control", id: "message-first-name" %>
          </div>

          <div class="form-group">
            <label for="message-last-name" class="col-form-label">Last Name:</label>
            <%= text_field_tag :last_name, nil, class: "form-control", id: "message-last-name" %>
          </div>

          <div class="form-group">
            <label for="message-email" class="col-form-label">Email address:</label>
            <%= text_field_tag :email, nil, class: "form-control", id: "message-email" %>
          </div>

          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea id="message-text" class="form-control" cols="30" rows="10"></textarea>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="send-message-to-agent">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image:url('<%= property_photo_url @property %>')">
  <div class="photo-overlay">

  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8">

      <div class="row">
        <div class="col-sm-4">
          <p class="h4 mb-2"><%= @property.for_sale? ? "For sale" : "For Rent" %></p>
          <p class="mb-0"><%= @property.address %></p>
          <p class="h2">
            <% if @property.for_sale? %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers Accepted" %>
            <% else %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open for enquiries" %> /
              month
            <% end %>
          </p>
        </div>

        <div class="col-lg-8 text-center">
          <div class="row mr-3 bg-light p-3">
            <div class="col-4">
              <p class="m-0"><strong><i class="fa-solid fa-bed mx-1 text-muted"></i></strong></p>
              <span class="lead"><%= @property.rooms %> Rooms</span>
            </div>
            <div class="col-4">
              <p class="m-0"><strong><i class="fa-solid fa-shower mx-1 text-muted"></i></strong></p>
              <span class="lead"><%= @property.bathrooms %> Bathrooms</span>
            </div>
            <div class="col-4">
              <p class="m-0"><strong><i class="fa-solid fa-car mx-1 text-muted"></i></strong></p>
              <span class="lead"><%= @property.parking_spaces %> Parking</span>
            </div>
          </div>
        </div>
      </div>
      <div class="row border-top border-bottom mt-3 mb-3 pt-4 pb-4">
        <div class="col-6">
          <strong>
            <% if @property.for_sale? %>
              <%= link_to "Est. monthly repayments
            of #{number_to_currency(((@property.price - @property.price * 0.1) / 360), precision: 0)}", '#', class: 'text-success' %>
            <% else %>
              <strong><%= @property.available_date.strftime("%a") %>, <%= @property.available_date.day.ordinalize %>
                <%= @property.available_date.strftime("%B") %></strong>
            <% end %>
          </strong>
        </div>
        <div class="col-6 text-end">
          <strong><%= link_to "Can I afford this property?", '#', class: 'text-success' %></strong>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p class="h3"><%= @property.name %></p>
          <p class="h4">Property description</p>
          <div id="property-details">
            <%= simple_format @property.details %>
          </div>

          <button class="btn btn-outline-info mt-3" id="toggleDetails">Read more</button>

          <% if @property.for_sale? %>
            <p class="my-3">* This rate is based on a 30 year mortgage, after paying an initial 10% down payment.
              Shorter term mortages would require a higher monthly repayment</p>
          <% end %>
        </div>
      </div>

    </div>
    <div class="col-sm-4">
      <%= render 'properties/agent_details', agent: @agent %>

      <div style="overflow:hidden;width: 320px;position: relative;">
        <iframe width="320" height="240" src="https://maps.google.com/maps?width=320&amp;height=240&amp;hl=en&amp;q=London%2C%20United%20Kingdom+(Title)&amp;ie=UTF8&amp;t=&amp;z=10&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        <div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;">
          <small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by
            <a href="https://embedgooglemaps.com/">Embed Google Maps</a> &
            <a href="https://xn--casinoutanspelgrnser-qzb.nu/">https:/casinoutanspelgränser.nu/</a></small></div>
        <style>#gmap_canvas img {
            max-width: none !important;
            background: none !important
        }</style>
      </div>
      <br/>
    </div>
  </div>

  <section class="my-5">
    <div class="container">
      <div class="row">
        <p class="h2">Other properties by this agent</p>
        <%= render 'properties/list', properties: @agent_properties %>
      </div>
    </div>
  </section>

</div>

<!-- Modal -->
<%= render "send_email_modal", agent: @agent %>