config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  root to: 'public#main'

  devise_for :accounts

  # site admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  # front-end version for unregistered users
  get '/blog', to: 'posts#latest', as: :blog

  # dashboard menu routes for registered users
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/profiles/:id', to: 'dashboard#profile', as: :profile

  # send email message to agent route
  post '/agent/message', to: 'properties#email_agent', as: :email_agent
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader

  scope :active, -> { where(active: true) }
  scope :latest, -> { order created_at: :desc}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, only: [:new, :create]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :can_access?, except: [:show, :latest]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  def latest
    @posts = Post.active
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        # format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def can_access?
    @show_sidebar = true
    unless current_account.admin?
      redirect_to root_url, flash: { danger: "You do not have access to view this page" } and return
    end
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :url, :summary, :body, :image, :image_cache, :active)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def post_thumbnail_url post
    post.image.thumb.present? ? post.image.thumb.url : asset_url("property-placeholder.jpg")
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
    <%= form.hidden_field :image %>

    <% if @post.image.present? %>
      <%= image_tag @post.image.thumb.url  %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <div class="property border">

      <div class="property-thumb" style="background-image: url(<%= post_thumbnail_url(post) %>)">
        <%= link_to "", post_path(post) %>
      </div>

      <div class="property-summary p-3">
        <h3 class="h3"><%= link_to post.title, post_path(post), class: "text-dark"%></h3>

        <p class="mt-2"><%= post.summary %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Summary</th>
      <th>Body</th>
      <th>Image</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.summary %></td>
        <td><%= post.body %></td>
        <td><%= post.image %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/latest.html.erb
<div class="container" id="home-banner">
  <div class="p-5 mb-4 bg-light rounded-3 banner">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Latest Blog Posts</h1>
      <p class="col-md-8 fs-4">Stay up to date with the latest news at Property Finder!</p>
<!--      <button class="btn btn-primary btn-lg" type="button">Example button</button>-->
    </div>
  </div>

  <% if @posts.empty? %>
    <p>No posts to display</p>
  <% else %>
    <% @posts.each do |post| %>
      <div class="row">
        <div class="col">
          <h2><%= post.title %></h2>
          <p><%= post.summary %></p>
          <%= link_to "Read more", post_path(post), class: "btn btn-success" %>
        </div>

      </div>
      <hr />
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold"><%= @post.title %></h1>
      <p class="text-muted p-lg-2"><em>Posted <%= time_ago_in_words @post.created_at %></em></p>
    </div>
  </div>
  <%= simple_format @post.body %>

  <p><%= link_to "View latest blog posts", blog_path %></p>
</div>